Revert unconditional error message
The condition and correct error is above, the reverted line
always leads to:
ERROR: DOCPATH: /usr/share/man does not match /usr/share/man
which is wrong.